//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVideoPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoID { get; set; }
        public string VideoName { get; set; }
        public string VideoAuthor { get; set; }
        public string VideoSize { get; set; }
        public string VideoUploadDate { get; set; }
        public string VideoPath { get; set; }
        public Nullable<bool> IsVideoActive { get; set; }
    }
}
